version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/

  place_remember:
    image: places_remember:latest
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - postgres
    volumes:
      - media_volume:/usr/src/app/media

  nginx:
    image: places_remember_nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../../static:/home/app/web/static
      - media_volume:/var/places_remember/media
    depends_on:
      - place_remember

volumes:
  media_volume: